# Generated by Django 2.2.3 on 2019-07-30 16:48

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year', models.IntegerField(blank=True, choices=[(2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], default=2019, help_text='year that event is being held', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(max_length=30, verbose_name='last name')),
                ('role', models.CharField(choices=[('arrangement', 'Arrangement'), ('designer', 'Designer'), ('programmer', 'Programmer'), ('talk team', 'Talk Team'), ('others', 'Others')], default='others', help_text="team's way of association in team", max_length=30)),
                ('bio', models.TextField(blank=True, help_text='description about person e.g. role in team achievements', null=True)),
                ('picture', models.ImageField(help_text="team's picture", upload_to='pics/team/')),
                ('linkedin_account', models.CharField(blank=True, help_text='linkedin.com/in/[User_Account]', max_length=100, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_organization', models.CharField(help_text='sponsor company', max_length=50)),
                ('name', models.CharField(help_text='sponsor person', max_length=50)),
                ('sponsor_type', models.CharField(choices=[('financial', 'Financial'), ('spiritual', 'Spiritual'), ('other', 'Other')], default='other', help_text='type of support', max_length=30)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
                ('about', models.TextField(help_text='about sponsor', max_length=1000)),
                ('logo', models.ImageField(default='default.jpg', help_text="company's logo", upload_to='pics/sponsors/')),
                ('account_status', models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive')], default='deactive', max_length=20)),
                ('event', models.ForeignKey(help_text='Choose Your Event:', on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(max_length=30, verbose_name='last name')),
                ('picture', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='pics/speakers/')),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('bio', models.TextField(max_length=500)),
                ('account_status', models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive')], default='deactive', max_length=20)),
                ('event', models.ForeignKey(blank=True, help_text='Choose Your Event:', null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
    ]
