# Generated by Django 2.2.3 on 2019-12-06 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speaker',
            name='event',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='event',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='event',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
