# Generated by Django 2.2.3 on 2019-12-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20191206_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(blank=True, choices=[('arrangement', 'Arrangement'), ('designer', 'Designer'), ('programmer', 'Programmer'), ('talk team', 'Talk Team'), ('others', 'Others')], default='others', help_text="team's way of association in team", max_length=30, null=True),
        ),
    ]
