# Generated by Django 2.2.3 on 2019-12-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20191206_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(blank=True, choices=[('curation', 'Curation'), ('organizer', 'Organizer'), ('coorganizer', 'Co Organizer'), ('marketing', 'Marketing'), ('documentation', 'Documentation'), ('creativity', 'Creativity'), ('frontend', 'Frontend Developer'), ('backend', 'Backend Developer'), ('designer', 'UI Designer')], default='others', help_text="team's way of association in team", max_length=30, null=True),
        ),
    ]
