# Generated by Django 2.2.8 on 2019-12-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_attendee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='bio',
        ),
        migrations.AddField(
            model_name='staff',
            name='instagram_account',
            field=models.CharField(blank=True, help_text='instagram.com/[User_Account]', max_length=100, null=True),
        ),
    ]
