# Generated by Django 2.2.8 on 2020-06-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntroduceSpeaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True)),
                ('S_fullname', models.CharField(blank=True, max_length=30, null=True)),
                ('S_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('S_reason', models.CharField(blank=True, max_length=30, null=True)),
                ('S_idea', models.CharField(blank=True, max_length=30, null=True)),
                ('number', models.CharField(blank=True, max_length=30, null=True)),
                ('verb', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
